spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

application:
  open-api-endpoints:
    - /users/login
    - /users/signup
    - /users/validate

user-service:
  url: http://user-service

authentication:
  token:
    prefix: Bearer

server:
  port: 8080