
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9091
